[package]
name = "hidden_text"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "s"
strip = "symbols"
lto = true
panic = "abort"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
