name: Release Binaries

on:
  release:
    types: [created]

jobs:
  build:
    name: Build release binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release
        run: cargo build --release

      - name: Archive binary
        run: |
          mkdir artifacts
          if [ "${{ runner.os }}" = "Windows" ]; then
            cp target/release/hide.exe artifacts/
          else
            cp target/release/hide artifacts/
          fi

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
